### ISSUE TITLE
Vietnamese translation to-do list

### ISSUE THREAD

**Issue by tetsureign** [shortthu/osu-web#1]
Finish this and we are good to go 😃

Let's do this fast cuz they add new strings ~~everyday~~ frequently

| Finished? | File name | Translator(s) | Reviewer(s) | PR |
| :---: | --- | --- | --- | :---: |
| x | [fulfillments](/shortthu/osu-web/blob/master/resources/lang/vi/model_validation/fulfillments.php) (**model_validation**) | @adv3006 | @shortthu | #3 |
| x | [payments](/shortthu/osu-web/blob/master/resources/lang/vi/model_validation/payments.php) (**model_validation**) | @adv3006 | @shortthu | #3 |
| x | [errors](/shortthu/osu-web/blob/master/resources/lang/vi/paypal/errors.php) (**paypal**) | @adv3006 | @shortthu | #3 |
| x | [accounts](/shortthu/osu-web/blob/master/resources/lang/vi/accounts.php) | @shortthu | - | - |
| x | [admin](/shortthu/osu-web/blob/master/resources/lang/vi/admin.php) | @adv3006 | @shortthu| #3 |
| x | [api](/shortthu/osu-web/blob/master/resources/lang/vi/api.php) | @shortthu | - | - |
| x | [artist](/shortthu/osu-web/blob/master/resources/lang/vi/artist.php) | @shortthu | - | - |
| x | [authorization](/shortthu/osu-web/blob/master/resources/lang/vi/authorization.php) | @Shortthu | @adv3006 | #14 |
| x | [bbcode](/shortthu/osu-web/blob/master/resources/lang/vi/bbcode.php) | @shortthu | @adv3006, @Gagako | #4 |
| x | [beatmap_discussion_posts](/shortthu/osu-web/blob/master/resources/lang/vi/beatmap_discussion_posts.php) | @Shortthu | @adv3006  | #8 |
| x | [beatmap_discussions](/shortthu/osu-web/blob/master/resources/lang/vi/beatmap_discussions.php) | @shortthu | @adv3006, @Gagako | #4 |
| x | [beatmappacks](/shortthu/osu-web/blob/master/resources/lang/vi/beatmappacks.php) | @shortthu | - | - |
| x | [beatmaps](/shortthu/osu-web/blob/master/resources/lang/vi/beatmaps.php) | @shortthu | @adv3006, @Gagako | #4 |
| x | [beatmapset_discussion_votes](/shortthu/osu-web/blob/master/resources/lang/vi/beatmapset_discussion_votes.php) | @shortthu | @adv3006  | #8 |
| x | [beatmapset_events](/shortthu/osu-web/blob/master/resources/lang/vi/beatmapset_events.php) | @shortthu | @adv3006  | #8 |
| x | [beatmapset_watches](/shortthu/osu-web/blob/master/resources/lang/vi/beatmapset_watches.php) | @shortthu | @adv3006  | #8 |
| x | [beatmapsets](/shortthu/osu-web/blob/master/resources/lang/vi/beatmapsets.php) | @shortthu | @adv3006  | #8 |
| x | [changelog](/shortthu/osu-web/blob/master/resources/lang/vi/changelog.php) | @shortthu | - | - |
| x | [common](/shortthu/osu-web/blob/master/resources/lang/vi/common.php) | @shortthu | - | - |
| x | [community](/shortthu/osu-web/blob/master/resources/lang/vi/community.php) | @adv3006 | @shortthu, @depzdai | #5 |
| x | [contest](/shortthu/osu-web/blob/master/resources/lang/vi/contest.php) | @shortthu | @adv3006 | #13
| x | [errors](/shortthu/osu-web/blob/master/resources/lang/vi/errors.php) | @shortthu | @adv3006 | #13
| x | [events](/shortthu/osu-web/blob/master/resources/lang/vi/events.php) | @shortthu | @adv3006 | #13
| x | [forum](/shortthu/osu-web/blob/master/resources/lang/vi/forum.php) | @Shortthu | @adv3006 | #14 |
| x | [friends](/shortthu/osu-web/blob/master/resources/lang/vi/friends.php) | @shortthu | - | - |
| x | [fulfillments](/shortthu/osu-web/blob/master/resources/lang/vi/fulfillments.php) | @shortthu | - | - |
| x | [help](/shortthu/osu-web/blob/master/resources/lang/vi/help.php) (*nothing here*) | @shortthu | - | - |
| x | [home](/shortthu/osu-web/blob/master/resources/lang/vi/home.php) | @shortthu | @adv3006 | #7 |
| x | [layout](/shortthu/osu-web/blob/master/resources/lang/vi/layout.php) | @shortthu | @adv3006 | #7 |
| x | [livestreams](/shortthu/osu-web/blob/master/resources/lang/vi/livestreams.php) | @Shortthu | @adv3006 | #14 |
| x | [model_validation](/shortthu/osu-web/blob/master/resources/lang/vi/model_validation.php) | @shortthu | @adv3006 | #19 
| x | [multiplayer](/shortthu/osu-web/blob/master/resources/lang/vi/multiplayer.php) | @Shortthu | @adv3006 | #17
| x | [news](/shortthu/osu-web/blob/master/resources/lang/vi/news.php) | @Shortthu | @adv3006 | #17 
| x | [password_reset](/shortthu/osu-web/blob/master/resources/lang/vi/password_reset.php) | @Shortthu | @adv3006 | #17 
| x | [rankings](/shortthu/osu-web/blob/master/resources/lang/vi/rankings.php) | @adv3006 | @shortthu, @depzdai | #5 |
| x | [status_page](/shortthu/osu-web/blob/master/resources/lang/vi/status_page.php) | @Shortthu | @adv3006 | #17
| x | [store](/shortthu/osu-web/blob/master/resources/lang/vi/store.php) | @shortthu | @adv3006 | #19 
| x | [supporter_tag](/shortthu/osu-web/blob/master/resources/lang/vi/supporter_tag.php) | @shortthu | - | - |
| x | [tournament](/shortthu/osu-web/blob/master/resources/lang/vi/tournament.php) | @shortthu | @adv3006, @Gagako | #18 
| x | [user_verification](/shortthu/osu-web/blob/master/resources/lang/vi/user_verification.php) | @shortthu | @adv3006, @Gagako | #18 
| x | [users](/shortthu/osu-web/blob/master/resources/lang/vi/users.php) | @shortthu | @adv3006 | #19 
| x | [validation](/shortthu/osu-web/blob/master/resources/lang/vi/validation.php) | @shortthu | @adv3006, @Gagako | #18 
| x | [wiki](/shortthu/osu-web/blob/master/resources/lang/vi/wiki.php) | @shortthu | @adv3006, @Gagako | #18

**Comment by shortthu** [comment]
test webhook

**Comment by tetsureign** [comment]
:trollface:
